#!/bin/bash
################################################################################
#
#  ripsacd
#
#  Simple script for ripping SACDs from a compatible Blu-ray player and
#  uploading them to a NAS via rsync.
#
################################################################################

sacd_server="172.16.8.86"  # Change to the IP address of your Blu-ray player
rip_flags="--2ch-tracks --output-dsf  --dsf-nopad"
rsync_target=  # where to upload sacd. eg., "my-synology:/volume1/music"

export PATH=~/bin:$PATH
command -v sacd_extract || (
  cd ~ || exit
  mkdir -pv ~/bin
  sudo apt update && sudo apt upgrade
  sudo apt install cmake git rsync
  git clone https://github.com/setmind/sacd-ripper.git
  cd sacd-ripper/tools/sacd_extract || exit
  cmake . && make
  if [ -x ./sacd_extract ]; then
    ln sacd_extract ~/bin/
  else
    echo "Build of sacd_extract failed. See above for details."
    exit 1
  fi
)

eval "$(
  sacd_extract --input "${sacd_server}":2002 --print |
  perl -ne 'print "$1=\"$2\"\n" if /^\t(\w+): (.*)/'
)"

Artist="$(echo "${Artist}" | tr -d '/\\;/')"
Title="$(echo "${Title}" | tr -d '/\\;/')"

output="${HOME}/sacd/${Artist}/${Title} (SACD)"
umask 002
mkdir -pv "${output}"
echo "----------------------------------------"
echo "Ripping ${Title} on $(date)"
# shellcheck disable=SC2086
if sacd_extract --input ${sacd_server}:2002 ${rip_flags} --output-dir "${output}"; then
  echo "----------------------------------------"
  echo "Rip complete on $(date)"
  # shellcheck disable=SC2010
  tmpdir="$(ls "${output}" | grep -v '\.dsf$')"
  [ -n "${tmpdir}" ] || exit 2
  mv "${output}"/"${tmpdir}"/*.dsf "${output}" && rmdir "${output}"/"${tmpdir}"
  if [ -n "${rsync_target}" ]; then
    rsync -avui --progress --stats --rsync-path=/usr/bin/rsync "${HOME}"/sacd "${rsync_target}"
  fi
else
  echo "Rip failed. See output above."
  exit 3
fi
